# Generated by Django 5.1.4 on 2025-01-23 22:55

import django.db.models.deletion
import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_course_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=schedule.models.get_default_department, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schedule.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default=schedule.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schedule.semester'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='course_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedule.courseassignment'),
        ),
    ]
