# Generated by Django 5.1.4 on 2025-01-23 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_timeslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedule.course'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.professor'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.room'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='type',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('DS', 'Devoir Surveillé'), ('EXAM', 'Examen'), ('SOUTENANCE', 'Soutenance Stage'), ('MILITARY', 'Encadrement militaire')], max_length=20),
        ),
    ]
