# Generated by Django 5.1.4 on 2025-01-25 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_courseassignment_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Étudiant'), ('CHEF_IRT', 'Chef de département IRT'), ('CHEF_GC', 'Chef de département GC'), ('CHEF_GE', 'Chef de département GE'), ('CHEF_GM', 'Chef de département GM'), ('CHEF_MPG', 'Chef de département MPG'), ('CHEF_SUD', 'Chef de département SUD')], max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
