# Generated by Django 5.1.4 on 2025-01-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='type',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('DS', 'Devoir Surveillé'), ('EXAM', 'Examen'), ('SPECIAL', 'Cours Spécial')], max_length=20),
        ),
    ]
